export const mockUsers = [
  {
    id: "1",
    firstName: "Chinedu",
    lastName: "Okafor",
    age: 28,
    email: "chinedu.o@example.ng",
    status: "active",
    role: "admin",
    createdAt: "2023-01-15",
    lastLogin: "2023-10-01",
  },
  {
    id: "2",
    firstName: "Ngozi",
    lastName: "Adeleke",
    age: 34,
    email: "ngozi.a@example.ng",
    status: "inactive",
    role: "editor",
    createdAt: "2022-05-20",
    lastLogin: "2023-09-15",
  },
  {
    id: "3",
    firstName: "Abubakar",
    lastName: "Bello",
    age: 22,
    email: "abubakar.b@example.ng",
    status: "pending",
    role: "viewer",
    createdAt: "2023-11-01",
    lastLogin: "2023-11-02",
  },
  {
    id: "4",
    firstName: "Fatima",
    lastName: "Danjuma",
    age: 30,
    email: "fatima.d@example.ng",
    status: "active",
    role: "viewer",
    createdAt: "2021-08-10",
    lastLogin: "2023-11-05",
  },
  {
    id: "5",
    firstName: "Oluwaseun",
    lastName: "Chukwu",
    age: 45,
    email: "oluwaseun.c@example.ng",
    status: "banned",
    role: "guest",
    createdAt: "2020-02-28",
    lastLogin: "2021-06-12",
  },
  {
    id: "6",
    firstName: "Adesua",
    lastName: "Balogun",
    age: 26,
    email: "adesua.b@example.ng",
    status: "active",
    role: "editor",
    createdAt: "2023-03-12",
    lastLogin: "2023-10-22",
  },
  {
    id: "7",
    firstName: "Emeka",
    lastName: "Ibrahim",
    age: 52,
    email: "emeka.i@example.ng",
    status: "inactive",
    role: "guest",
    createdAt: "2019-11-05",
    lastLogin: "2020-01-15",
  },
  {
    id: "8",
    firstName: "Chioma",
    lastName: "Usman",
    age: 31,
    email: "chioma.u@example.ng",
    status: "active",
    role: "admin",
    createdAt: "2022-07-19",
    lastLogin: "2023-11-10",
  },
  {
    id: "9",
    firstName: "Ibrahim",
    lastName: "Adeyemi",
    age: 40,
    email: "ibrahim.a@example.ng",
    status: "pending",
    role: "viewer",
    createdAt: "2023-09-01",
    lastLogin: "2023-09-02",
  },
  {
    id: "10",
    firstName: "Zainab",
    lastName: "Nwachukwu",
    age: 29,
    email: "zainab.n@example.ng",
    status: "active",
    role: "editor",
    createdAt: "2023-05-14",
    lastLogin: "2023-11-11",
  },
  {
    id: "11",
    firstName: "Babatunde",
    lastName: "Olatunji",
    age: 38,
    email: "babatunde.o@example.ng",
    status: "active",
    role: "admin",
    createdAt: "2021-12-01",
    lastLogin: "2023-11-09",
  },
  {
    id: "12",
    firstName: "Amina",
    lastName: "Musa",
    age: 25,
    email: "amina.m@example.ng",
    status: "inactive",
    role: "viewer",
    createdAt: "2022-02-15",
    lastLogin: "2023-08-20",
  },
  {
    id: "13",
    firstName: "Uche",
    lastName: "Lawal",
    age: 42,
    email: "uche.l@example.ng",
    status: "active",
    role: "editor",
    createdAt: "2020-10-10",
    lastLogin: "2023-11-12",
  },
  {
    id: "14",
    firstName: "Nneka",
    lastName: "Okeke",
    age: 27,
    email: "nneka.o@example.ng",
    status: "pending",
    role: "guest",
    createdAt: "2023-08-05",
    lastLogin: "2023-08-05",
  },
  {
    id: "15",
    firstName: "Yusuf",
    lastName: "Agbaje",
    age: 50,
    email: "yusuf.a@example.ng",
    status: "banned",
    role: "viewer",
    createdAt: "2018-04-22",
    lastLogin: "2022-12-01",
  },
  {
    id: "16",
    firstName: "Aisha",
    lastName: "Eze",
    age: 33,
    email: "aisha.e@example.ng",
    status: "active",
    role: "admin",
    createdAt: "2022-11-11",
    lastLogin: "2023-11-01",
  },
  {
    id: "17",
    firstName: "Segun",
    lastName: "Obi",
    age: 47,
    email: "segun.o@example.ng",
    status: "inactive",
    role: "editor",
    createdAt: "2019-06-30",
    lastLogin: "2023-05-18",
  },
  {
    id: "18",
    firstName: "Tolulope",
    lastName: "Abdullahi",
    age: 24,
    email: "tolulope.a@example.ng",
    status: "active",
    role: "viewer",
    createdAt: "2023-10-12",
    lastLogin: "2023-11-10",
  },
  {
    id: "19",
    firstName: "Ebuka",
    lastName: "Salami",
    age: 36,
    email: "ebuka.s@example.ng",
    status: "pending",
    role: "guest",
    createdAt: "2023-07-25",
    lastLogin: "2023-07-26",
  },
  {
    id: "20",
    firstName: "Kemi",
    lastName: "Bakare",
    age: 29,
    email: "kemi.b@example.ng",
    status: "active",
    role: "editor",
    createdAt: "2021-03-08",
    lastLogin: "2023-10-30",
  },
];
